#Configuraci칩n b치sica del servidor
server:
  port: 8888
  servlet:
    context-path: /

#Configuraci칩n b치sica de logs
logging:
  level:
    ROOT: ERROR
    org.springframework.web: ERROR
    com.ultrachus.springboot.rest.example.springbootjpahibernateh2: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: C:\Users\jgomez\Desktop\ProyectosCursos\logs\spring-boot-jpa-hibernate-h2.log